feature(whl): add multiprocess support
kxzxvbk/Fling pull request #6
Opened 2023-07-22 15:02 UTC by kxzxvbk

Bugs or todos:
- This code might only work on well on Linux
- Do not support torch.compile(model)
- The acc of model does not seem to be normal (very low)

2023-07-23 10:10 UTC, XinghaoWu requested changes
The bug about MultiPorcess.

2023-07-23 10:10 UTC, XinghaoWu commented on fling/utils/mp_utils.py
> +                results = pool.starmap(client_trainer, tasks)
After my tests and my research, I found that ’Multiprocess‘ uses ’fock‘ to create child processes that copy variables from the main process. Therefore, the ’tasks‘ you pass in here will be **deeply copied** by the main process. After the multi-process training is complete, the clients' model in the main process is not updated。
In this code framework, one solution is to return 'model.state_dict()' in the client's 'train' function and execute 'load_state_dict()' in the pipeline.  In my tests, it works.

2023-07-23 15:47 UTC, kxzxvbk commented
PyTorch2.0 Benchmark: 
A100 GPU + 4 core CPU + MNIST + CNN + batchsize=32
- num_proc = 1, total time per round = 21.7s
- **num_proc = 2, total time per round = 14.9s**
- num_proc = 3, total time per round = 15.3s
- num_proc = 4, total time per round = 16.5s
- num_proc = 8, total time per round = 25.2s

A100 GPU + 4 core CPU + CIFAR10 + resnet8 + batchsize=32
- num_proc = 1, total time per round = 45.2s
- num_proc = 2, total time per round = 32.1s
- num_proc = 3, total time per round = 30.1s
- num_proc = 4, total time per round = 32.5s
- num_proc = 8, total time per round = 40.4s

2023-07-24 06:14 UTC, XinghaoWu reviewed
A suggestion to improve the efficiency.

2023-07-24 06:14 UTC, XinghaoWu commented on fling/utils/mp_utils.py
> +            for client in clients:
Here might be able to simplify. The results of 'starmap' execution are ordered.

2023-07-25 01:26 UTC, merged